routes.js

Motivation is two-fold: 
1. The sourcemaps (`.map` files) are present in the `static` dir, just not being used
2. 404 errors in server logs are annoying (when you have Chrome Dev Tools open, chrome will look for `.map` files)

Serve asset sourcemaps

---

static/index.html

Currently, if we try to register fastify-swagger inside a [route-prefixed plugin](https://github.com/fastify/fastify/blob/master/docs/Routes.md#route-prefixing), 
when we try to use the Swagger UI, we see in big letters "Failed to load spec." (and a message like `GET http://localhost:3002/documentation/json 404 (Not Found)` in the browser console).
This PR fixes the URL used to load the spec (`./documentation/json`), so that it's directory is the same as the other assets (e.g. `./documentation/swagger-ui.css`) which already work with prefixed paths.

Support serving `/documentation` from prefixed path

---

index.js
test/swagger.js

Fixes deprecated route. Example setting deprecated in image below:

fix deprecated route #14

---

index.js
package.json

Changes to `fastify-swagger` to make it compatible with `fastify` `0.43.0`:
- Use onRoute Hook instead of iterator
- Update version of the `fastify` dependency
Implemented #22 
Fixes #26

Use onRoute Hook instead of iterator

---

index.js
test/swagger.js

In swagger documentation the `consumes` property can be specified at top level or on a per-route basis. 
This PR adds the `consumes` property if specified at route level. This is important for swagger-ui too insofar as users can "try out" endpoints only with the content-type specified per route

add route consumes to swagger documentation

---

index.js
test/swagger.js

https://github.com/fastify/fastify-formbody parses request body regardless of whether content-type is json or application/x-www-form-urlencoded
However, swagger has different schemas for json and application/x-www-form-urlencoded, multipart/form-data
This PR distinguishes between the two

Parse request form params

---

README.md
routes.js
static/index.html
test/route.js

Started to integrate my swagger plus OAuth security schema and met an issue with `fastify-swagger`.
Seems we are only serving `index.html`, but not the other file.
Plus, right now it's not actually possible to use it under the url `/documentation/` (it will serve html, but  will not be able to load `css` and `js`). Therefore I've changed the paths to the absolute ones.
It works both `/documentation` and `/documentation/` right now.
As per `oauth2-redirect.html` - starting to serve it.
~~seems to be good, but I did not check the full cycle yet.~~
I can confirm that the full cycle "works on my machine".

serving oauth2-redirect.html; /documentation => /documentation/;

---

routes.js

I'm sorry, there was a 🐞 .
root was resolving into the root of the project folder, not the module folder. I've realised it only after I've installed v0.7.0 into my project.

correctly resolving static folder

---

dynamic.js
test/swagger.js

fastify already supports required query params, this little change reflects that on the generated swagger
PS: recreated PR because I pushed the previous commits without my github email

implemented required for query params

---

.gitignore
README.md
dynamic.js
examples/dynamic-overwrite-endpoint.js
routes.js
static.js
test/route.js

- Adding the ability to customize the swagger end-point by passing `routePrefix` 
- use `/documentation` by default
@mcollina

adding the ability to change swagger url

---

package.json
routes.js
test/route.js

Fix: redirect to index

---

README.md
static.js
tap-snapshots/test-static.js-TAP.test.js
test/static.js

🤚,
I suggest to introduce an option of `postProcessor` to be able dynamically adjust the static file, for example based on the environment you run your application on.
My use case - I have auth integrated into the swagger specification:
```
oAuth2Code:
type: oauth2
description: OAuth
flows:
authorizationCode:
authorizationUrl: https://localhost:9000/and/it/goes/further
tokenUrl: https://localhost:9000/and/it/goes/further
scopes:
adminLogin: "Login as admin"
```
These urls are different for `localhost`/`development`/`staging`/`whatever`.
Having a `postProcessor` option will allow me to inject them based on the `NODE_ENV` and `config`, at the same time keeping something as the default value.
Regards,

introducing postProcessor for static mode

---

static.js
tap-snapshots/test-static.js-TAP.test.js
test/static.js

resolves #97 by adding `document` property which accepts valid JavaScript object (already loaded & parsed swagger specification)

feature: support explicitly passed document #97

---

dynamic.js
test/swagger.js

For the following schema configure:
```
{
params: {
type: 'object',
properties: {
enumKey: {type: 'string', enum: ['enum1', 'enum2']}
}
}
}
```
the expected swagger json result should not omit the **enum: ["enum1", "enum2"]** part

enum configures in path params is missing

---

README.md

https://github.com/fastify/fastify-swagger/issues/122 securityDefinitions apiKey needs to be spelled the same as route security apiKey

Make Security Definitions example align

---

index.d.ts
package.json
tsconfig.json
types.test.ts

Issue Reference #118 
This adds Typescript types in the project.
It uses the [@types/swagger-schema-official](https://www.npmjs.com/package/@types/swagger-schema-official) as a schema for the options.
While looking at it, I found 4 properties on the schemas that I didn't find in this library
```
swagger: string;
paths: { [pathName: string]: Path };
parameters?: { [parameterName: string]: BodyParameter | QueryParameter };
responses?: { [responseName: string]: Response };
```

Add TypeScript types

---

package.json

My package.json contains:
```
"dependencies": {
"fastify-plugin": "^1.3.0",
"fastify-swagger": "^0.16.1",
...
"protobufjs": "^6.8.8",
"revane": "^1.0.1",
"revane-fastify": "^0.3.0",
"thunk-redis": "^2.2.3"
},
```
I call `$ npm run test` and get the following error message
```
> article-service@1.0.0 test /home/plipp/work/OBI/obi-neu/article-service
> npm run compile && npm run unit
> article-service@1.0.0 compile /home/plipp/work/OBI/obi-neu/article-service
> tsc
node_modules/fastify-swagger/index.d.ts:3:32 - error TS2307: Cannot find module 'swagger-schema-official'.
3 import * as SwaggerSchema from 'swagger-schema-official';
~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! article-service@1.0.0 compile: `tsc`
npm ERR! Exit status 2
npm ERR! …
```

swagger-schema-official is now required externally, thus put to 'dependencies'

---

README.md
index.js
package.json
routes.js
test/route.js

Tests fail but I couldn't figure out. The redirect for `/documentation` -> `/documentation/index.html` does not return any payload for some reason
Failing test: https://github.com/fastify/fastify-swagger/blob/master/test/route.js#L286
Failing line: https://github.com/fastify/fastify-swagger/blob/master/routes.js#L14
Any ideas?

Fixes for fastify v2

---

README.md
dynamic.js
index.d.ts
package.json
test/transform.js
types.test.ts

Add a transform option to convert `route.schema` on documentation generation in `dynamic` mode.

Add a transform method for schema

---

dynamic.js
test/swagger.js

Hi,
this fixes `basePath` support when routes are defined with prefixes.
Best,
Patrick

Fix `basePath` support

---

dynamic.js
test/swagger.js

This is an optional field: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-5

Bugfix missing `operationid` and `produces` route property

---

index.d.ts

Fixes `TS2322: { hide: boolean; } is not assignable to type 'RouteSchema'`
```typescript
const schema: RouteSchema = {hide: true};
```

Added hide property to RouterSchema

---

http2-types.test.ts
index.d.ts
types.test.ts

The old typing throws TypeError when using `security: []` definition in endpoint schema:
Workaround for that is to use `[{}]` as seen with `const b`, but that in turn confuses Swagger UI which renders it as secured, pre-authenticated endpoint:
This new typing fixes that:

Fix typing: array definition

---

README.md

The default of `exposeRoute` is `false` which leads to a 404 error:
{"message":"Route GET:/documentation not found","error":"Not Found","statusCode":404}

Add "exposeRoute:true" in usage example

---

README.md
examples/collection-format.js

As requested in https://github.com/fastify/fastify-swagger/issues/178#issuecomment-582627553
This documents how to set Open API-specific parameter options in a schema used for parsing query strings.

docs: document how to set OA-specific parameter options

---

dynamic.js
test/swagger.js

Fixes #232 
I personally would remove the whole thing about stripping the basePath from paths, but since that would be a breaking change I decided against it.

Ensure paths start with a leading slash

---

index.d.ts
test/types/http2-types.test.ts
test/types/types.test.ts

Partial revert of https://github.com/fastify/fastify-swagger/pull/238/commits/530514a394c58fa8d26b5084a813de2b49a42d17 which broke the types declared in this plugin. I can't find anything in the PR or commit message that explains why this was done, but this module does not have a default export.
Fixes: #260

fix: Correct types

---

index.d.ts
test/types/types.test.ts

Make FastifyDynamicSwaggerOptions, FastifyStaticSwaggerOptions & SwaggerOptions exported for cases like:
```ts
import fastifySwagger, { SwaggerOptions } from 'fastify-swagger'
const options: SwaggerOptions = {
...
}
app.register(fastifySwagger, options)
```
This was possible in v2

Export ts types

---

README.md
dynamic.js
index.d.ts
test/swagger.js
test/types/types.test.ts

This PR addresses : https://github.com/fastify/fastify-swagger/issues/277
Chose the `X-HIDDEN` attribute but have no strong opinion on it.

feat: add Tag handling to hide route

---

.taprc
index.d.ts
index.js
package.json
test/esm/esm.mjs
test/esm/index.test.js
test/types/http2-types.test.ts
test/types/imports.test.ts
test/types/types.test.ts

This PR is the result of the ongoing talks about supporting all import contexts for the fastify ecosystem. We can use it as a case study for other core plugins.
What is important to note is that it is not enough to add this code only at JS, since the exported typings need to be updated too.
- Adds the "infamous triplet" in `module.exports`
- Replaces namespace export with "infamous triplet" in TypeScript typings
- Adds test for all TS imports
- Adds test for ESM context

Adds the "infamous triplet" and exports default and names exports in TypeScript types

---

dynamic.js
test/json-schema.test.js

Added support for description in response keys (status code) 
Like this example (present in bug #299):
```javascript
response: {
200: {
type: 'object',
properties: {
hello: { type: 'string' },
},
description: 'some description'
}
}
```

Fix bug #299 Response description prop is not appended correctly to schema definition

---

dynamic.js
test/swagger.js

Linked to issue https://github.com/fastify/fastify-swagger/issues/316
No need to update the doc as this is the expected behaviour of what's currently described in the section about hiding routes

fix: execute transform(schema) before checking schema.hide and hiddenTag

---

README.md
dynamic.js
index.d.ts
test/swagger.js
test/types/types.test.ts

feature: when `stripBasePath` is set to false, do not strip basePath

---

index.d.ts
test/types/types.test.ts

OperationId is handled in the code [here](https://github.com/fastify/fastify-swagger/blob/master/dynamic.js#L166) but not in the ts types.
This Pull request add the operationId field to the `FastifySchema` type.
`operationId` is described here : https://swagger.io/docs/specification/paths-and-operations/

add operationId to types

---

dynamic.js
test/swagger.js

Fixes #304, but I'm not super fan of the implementation. 
I'm missing an update on the type definitions, but I can't express `Partial<SwaggerSchema.Spec>` and properties starting by `x-`. Do you have any preferences about what to do with that?

fix: include swagger extensions if define at the root

---

index.d.ts
package.json
test/types/http2-types.test.ts
test/types/imports.test.ts
test/types/minimal-openapiV3-document.ts
test/types/types.test.ts

Closes #327
The type of the property 'document' in the interface StaticDocumentSpec in the file 'index.d.ts' was formerly specified as 'string' and was corrected to object.
I think one could even specify it as one of
- SwaggerSchema.Spec (for swagger V2 specs -already imported) or
- OpenApi3Spec (for OpenApi V3 specs - where can this come from?)
Are there other versions that would then need to be supported?

Fix type of StaticDocumentSpec.document in index.d.ts

---

package.json

This moves `openapi-types` to dependencies so that the typescript types in `index.d.ts` work correctly.
Fixes #340 

fix(deps): Correctly add openapi-types to dependencies

---

README.md
lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

Resolve: #250
Caption from [swagger](https://swagger.io/docs/specification/describing-responses/)
`
To define a range of response codes, you may use the following range definitions: 1XX, 2XX, 3XX, 4XX, and 5XX. If a response range is defined using an explicit code, the explicit code definition takes precedence over the range definition for that code.
`
I do not introduce a new option as @Eomm suggestion. It will also not throwing error because it may break someone code.
Behavior for Swagger 
- When I see `Nxx` status code, transform it to `200` status code.
- If we find conflict of `200` status code, drop the transformed one as it is more general response.
- Append the transformed status code to response.
Behavior for OpenAPI
- All `Nxx` status code will enforce upper case.
- Append the …

Fix swagger nxx response

---

.github/dependabot.yml
.github/workflows/ci.yml
README.md
package.json

Main purpose of this pull request is to update the readme to remove mention of OpenAPI v3.\*.\* being unsupported, as #333 adds this functionality.
Ended up getting carried away and adding a few extra badges and coveralls coverage generation into the CI as well. 😄 

Update readme and CI

---

README.md
lib/mode/dynamic.js
lib/routes.js
lib/util/prepare-swagger-ui.js
package.json
test/route.js

This PR allows to pass a dynamic configuration to the generated swagger UI. The option that should be used in the plugin configuration in order to accomplish that is `uiConfig`.
Configuration docs: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
Since there is an issue configuring `swagger-ui-dist` (that distributes only static files, see https://github.com/swagger-api/swagger-ui/issues/5710) without changing the content of the static assets, the only way to configure the UI with a dynamic external configuration is by editing the `index.html` file and the script within that loads the swagger ui in the page.
There were two approaches:
1. Intercepting the `index.html` request on the documentation routes and distributing an altered html file that load …

feat: pass swagger-ui additional configuration

---

README.md
lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

This PR used to fix the existing bug of handling empty body and add the function for setting response header.
Resolve: #313
Resolve: #335
It is a little bit bulky in `openapi` implementation, as we need to transform most of the schema.
Header Behavior for Swagger:
- add `headers` in response
- remove `headers` from schema 
Header Behavior for OpenAPI:
- add `headers` in response which need to do some `transformation`
- remove `headers` from schema
Note: we must use the keyword `delete` in here because `swagger.validate` itself will validate invalid field even you set it as `undefined`.
Empty Body Behavior:
- we only add `schema` into `response` when status code is not equal to 204
Note: we need to cast status code to `string` to ensure the check pass.
and the [Code of …

feat: response headers and empty body

---

lib/mode/static.js
test/mode/static.js

fix: static ui config is missing

---

README.md
lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

Any description provided in a response schema was also used for the response itself.
For example, this route:
```js
fastify.get('/description', {
schema: {
response: {
200: {
description: 'response and schema description',
type: 'string'
}
}
}
}, () => {})
```
generated this schema:
```json
{
"/description": {
"get": {
"responses": {
"200": {
"description": "response and schema description",
"schema": {
"description": "response and schema description",
"type": "string"
}
}
}
}
}
}
```
The existing behavior stands, but you can also provide an independent description of the response via the `responseDescription` field.
For example, this route:
```js
fastify.get('/responseDescription', {
schema: {
response: {
200: {
responseDescription: 'description for the response as a whole',
description: …
```

Transform Fastify schema.responseDescription to OAS response.description  [#336]

---

lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
lib/util/common.js
test/mode/static.js

This change addresses a regression when bundling with webpack after upgrading from v3 to v4 of this plugin.
The plugin fails after bundling because the `package.json` of this library is not present in the expected relative location and an attempt is made to read from an `undefined` object.

Default pkg to empty object in case readPackageJson fails

---

lib/spec/openapi/utils.js
test/spec/openapi/route.js
test/spec/openapi/schema.js

Changes
- parameters trigger `delete` only if it is needed
- fix description is missing for `path`, `cookies` and `query`
- fix test case typo

fix: openapi parameters description

---

lib/util/common.js
test/util.js

neither OpenAPI nor Swagger support `RegExp` in path, so we cannot support all the path like `fastify` does.
More Info: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#path-templating
Changes:
- add support for url like `/example/near/:lat-:lng/radius/:r`
Close: #100 

fix: multiple path params cannot be recognize within two brackets

---

README.md
package.json
test/transform.js

actually, the issue was with the used transformation lib
changed to one which is updated more recently
closes #373

fix: joi transform

---

examples/dynamic-openapi-joi.js

chore: add dynamic openapi joi example

---

README.md
index.d.ts
lib/mode/dynamic.js
lib/routes.js
lib/util/prepare-swagger-ui.js
test/route.js
test/types/types.test.ts

Following the approach of https://github.com/fastify/fastify-swagger/pull/351, this PR aims to make the Configuration options for [Swagger UI initOAuth](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/) configurable in a dynamic way.

feat: pass swagger-ui initOAuth config

---

index.d.ts
lib/mode/static.js
test/mode/static.js
test/types/types.test.ts

Changes:
- fix uiConfig typings is missing
- fix initOAuth cannot be customize in static mode

fix: uiConfig types and initOAuth in static mode

---

.github/workflows/ci.yml
package.json

Had to swap out single quotes in test scripts with escaped double quotes, as Windows fails with single quotes.

ci: add `matrix.os` array to test on other os

---

lib/spec/openapi/utils.js
test/spec/openapi/schema.js

When using `default: null` in a schema, and fastify-swagger is configured to output OpenAPI 3.0, this error will happen:
```
FAIL  test/spec/openapi/schema.js
✖ Cannot convert undefined or null to object
test: support default=null
stack: |
Function.keys (<anonymous>)
transformDefsToComponents (lib/spec/openapi/utils.js:81:12)
forEach (lib/spec/openapi/utils.js:85:27)
Array.forEach (<anonymous>)
transformDefsToComponents (lib/spec/openapi/utils.js:81:29)
forEach (lib/spec/openapi/utils.js:200:22)
Array.forEach (<anonymous>)
resolveResponse (lib/spec/openapi/utils.js:198:15)
prepareOpenapiMethod (lib/spec/openapi/utils.js:284:29)
Object.swagger (lib/spec/openapi/index.js:45:29)
type: TypeError
```

fix error when using default=null

---

README.md
examples/dynamic-openapi.js
examples/dynamic-swagger.js
lib/mode/dynamic.js
lib/spec/openapi/index.js
lib/spec/openapi/utils.js
lib/spec/swagger/index.js
lib/spec/swagger/utils.js
lib/util/common.js
test/spec/openapi/option.js
test/spec/swagger/option.js

Added a new plugin parameter **hideUntagged**.
Added cases in both dynamic swagger and openapi example
Added tests cases in both dynamic swagger and openapi
Update readme with the new parameter description
Related issue: https://github.com/fastify/fastify-swagger/issues/403

added option to hide untagged routes

---

README.md
examples/options.js
lib/spec/openapi/index.js
lib/spec/swagger/index.js
test/spec/openapi/route.js
test/spec/swagger/route.js

As titled, this PR adds support for OpenAPI Links. This feature is OpenAPI v3 specific.
I did a somewhat different approach as it is not part of the schema.
Let me know if the place where I put those new options is ok or not.

Add OpenAPI Links support

---

lib/spec/openapi/utils.js
test/spec/openapi/option.js

Changes:
- For single value `examples` it should be converted to `example` object
Related issue: https://github.com/fastify/fastify-swagger/issues/421

fix: single value examples should be converted to example

---

lib/spec/openapi/utils.js
test/spec/openapi/schema.js

Initially solved by @schantaraud, and referenced in https://github.com/fastify/fastify-swagger/pull/395, I've added tests specifically for this and solved #394 

fix(openapi): fix global schema references in fastify

---

README.md
lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

Related issue: https://github.com/fastify/fastify-swagger/issues/434
OpenAPI generated schema
```yaml
openapi: 3.0.3
info:
version: 4.8.2
title: fastify-swagger
components:
schemas: {}
paths:
/:
get:
responses:
'204':
description: No Content
'503':
description: Service Unavailable
```
Swagger generated schema
```yaml
swagger: '2.0'
info:
version: 4.8.2
title: fastify-swagger
definitions: {}
paths:
/:
get:
responses:
'204':
description: No Content
'503':
description: Service Unavailable
```

Allows to define empty response body for any status code

---

index.d.ts
package.json
test/types/types.test.ts

No code changes. Just expose an option on the interface to make nice for us ts users.
satisfy #191 
- [x ] run `npm run test` and `npm run benchmark`
- [x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)

Add validatorUrl to the FastifySwaggerOptions interface

---

index.d.ts
test/types/types.test.ts

Why:
I wanna add a type for uiConfig on the project [@nestjs/swagger](https://github.com/nestjs/swagger/blob/5bf65b9d16bc5d9dfd6119b3e87af85439830da0/lib/interfaces/swagger-custom-options.interface.ts#L16) but upstream `fastify-swagger` doesn't export that.

feat: Extract the type of initOAuth and uiConfig

---

README.md
examples/dynamic-swagger.js
lib/mode/dynamic.js
lib/util/common.js
package.json
test/spec/openapi/schema.js

This PR:
- fixes the **swagger UI layout** to show the schema's `$id` as model name (see screenshot at the bottom). Under the hood, the `def-0` renaming is still in place.
- adds documentation to describe what is happening under the hood.
- adds the option to customize the `$ref`'s link into the inline schema. This gives to the user the chance to do what he/she wants and remove totally the `def-0` logic.
I think this (too simple?) solution solves the case.
Feel free to give feedback about this PR
To avoid a major bump, this PR fixes the view issue without breaking the `def-0` logic that has been developed to protect users actually 😄 
Let me explain.
This JSON Schema has a relative URI `$id`. 
```
fastify.addSchema({
$id: 'user',
type: 'object',
definitions: {
id: {
type: 'string', …
```

feat: customize def-0 model name

---

README.md
examples/dynamic-openapi.js
examples/dynamic-swagger.js
lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

Related issue: https://github.com/fastify/fastify-swagger/issues/441
OpenAPI 3 generated schema
<details>
<summary>Click to expand</summary>
```yaml
openapi: 3.0.3
info:
version: 4.10.0
title: fastify-swagger
components:
schemas: {}
paths:
/:
get:
responses:
'200':
description: Expected Response
content:
application/json:
schema:
description: Expected Response
type: object
properties:
foo:
type: string
default:
description: Default Response
content:
application/json:
schema:
description: Default Response
type: object
properties:
bar:
type: string
```
</details>
Swagger generated schema
<details>
<summary>Click to expand</summary>
```yaml
swagger: '2.0'
info:
version: 4.10.0
title: fastify-swagger …
```

chore: add support for "default" parameter

---

README.md
lib/mode/dynamic.js
lib/mode/static.js
lib/routes.js
package.json
test/hooks.js

feat documentation authorization

---

lib/spec/openapi/index.js
lib/spec/openapi/utils.js
test/spec/openapi/refs.js

OpenApi : nested ref in #/components/schemas/

---

lib/spec/openapi/utils.js
test/spec/openapi/refs.js

When a response schema is created with a `$ref` not at first level (as in the added test), the openapi spec is not valid because of the `$id` key from the added schema.
Here the output of the test before (not a valid oas)
```yml
openapi: 3.0.3
info:
version: 4.12.1
title: fastify-swagger
components:
schemas:
order:
type: string
enum:
- foo
paths:
/:
post:
responses:
'200':
description: Default Response
content:
application/json:
schema:
type: object
properties:
order:
$id: order
type: string
enum:
- foo
```
and after the change (this is valid because order does not contains the `$id` key):
```yml
openapi: 3.0.3
info:
version: 4.12.1
title: fastify-swagger
components:
schemas:
order:
type: string
enum:
- foo
paths:
/:
post:
responses:
'200':
description: Default Response
content: …
```

fix: generate correct openapi with response schema containing ref

---

lib/spec/openapi/index.js
lib/spec/openapi/utils.js
lib/spec/swagger/index.js
lib/spec/swagger/utils.js
test/spec/openapi/refs.js
test/spec/swagger/refs.js

related to https://github.com/fastify/fastify-swagger/pull/478 and https://github.com/fastify/fastify-swagger/pull/472
Fixes nested + complex ref's when using the swagger spec

fix: nested swagger ref

---

lib/util/common.js
test/util.js

Fixes #510 
I am a bit tired on updating the regexp to accept a lot of different format of param.
I reverted back to use a single `for-loop`
Notable Changes:
1. it support non-named regexp
2. it support `*`
Both of the above cases use auto-generated param name.

fix: format param url

---

lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

This PR solve #165 issue. 
The idea is to transform the patternProperties into a valid OpenAPI definition. We lost the precision in public documentation but validation still done on server side  

feat(openapi): support patternProperties

---

examples/options.js
lib/spec/openapi/utils.js
test/spec/openapi/route.js

Fix for a bug, when `stripBasePath` is disabled and openApi is configured. it will not map path params to fastify params.

OpenApi: Fix params mapping on relative URL

---

index.d.ts
lib/spec/swagger/utils.js
test/spec/swagger/route.js
test/types/types.test.ts

This pull request adds the possibility of specifying an `externalDocs` object per route when using OAS 2.0 ([as described here](https://swagger.io/specification/v2/#operationObject)) and also exposes this option in the `FastifySchema` interface.
This was already supported by the library when using OAS 3.0 ([as seen here](https://github.com/fastify/fastify-swagger/blob/a0ca54ad45465b8d5a7717c86d1dc57244c843af/lib/spec/openapi/utils.js#L326)), but was not exposed in the `FastifySchema` interface and was also not available when using OAS 2.0.

adds support to externalDocs per route when using OAS 2.0 and updates FastifySchema interface

---

lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/option.js

This MR add in open-api optional "required" property on schema body if exist at least one required properties in his schema.
It should solve https://github.com/fastify/fastify-swagger/issues/539 issue.

feat(open-api): add required on body if necessary

---

index.d.ts
test/types/types.test.ts

This PR adds the missing `deprecated` boolean to the schema types

Added missing "deprecated" type on schema

---

lib/spec/openapi/utils.js
test/spec/openapi/refs.js

* Add test for failing use case
* Implement fix
Fix #553.

Support ref relative pointers in openapi params

---

README.md

[fastify-openapi-glue](https://www.npmjs.com/package/fastify-openapi-glue) instead of deprecated [fastify-swaggergen](https://github.com/seriousme/fastify-swaggergen) by the same author.

Link to fastify-openapi-glue

---

lib/spec/openapi/utils.js
lib/util/common.js
package.json
test/spec/openapi/refs.js

Without the fix the test would have returned a 400 error for the second POST call. This is because running swagger mutates the schema in the global Fastify instance, and breaks the validation. 
This fix clones the schema when we load it in the Fastify swagger package and prevents mutation.

Clone schemas

---

lib/spec/openapi/utils.js
lib/util/common.js
test/hooks.js

Currently, the top-level `fastify.addSchema` cannot be catched.

fix: top level schema

---

README.md
index.js
lib/util/common.js
package.json
test/csp.js
test/decorator.js
test/esm/esm.mjs
test/esm/index.test.js
test/hooks.js
test/integration.js
test/mode/static.js
test/route.js
test/spec/openapi/option.js
test/spec/openapi/refs.js
test/spec/openapi/route.js
test/spec/openapi/schema.js
test/spec/swagger/option.js
test/spec/swagger/refs.js
test/spec/swagger/route.js
test/spec/swagger/schema.js
test/transform.js
test/util.js

`@fastify/swagger` now require to `await` in order to inspect the `routes`.
We skip `HEAD` route as it duplicate of any added `GET` route.

feat: support fastify v4

---

lib/spec/openapi/utils.js
test/spec/openapi/option.js

fix: allow openapi version to be overridden

---

lib/spec/openapi/utils.js
lib/util/common.js
package.json
test/mode/static.js
test/route.js
test/spec/openapi/option.js
test/spec/openapi/refs.js
test/spec/openapi/route.js
test/spec/openapi/schema.js
test/spec/swagger/option.js
test/spec/swagger/refs.js
test/spec/swagger/route.js
test/spec/swagger/schema.js

fix: $ref in allOf in query/headers causes Fastify to crash

---

lib/spec/openapi/utils.js
test/spec/openapi/option.js

Hi! Fixes Issue #535 
Moved the example and examples fields to the level above. Now the scheme is valid and displays correctly in swagger.

Move example and examples object to media (Fix #535)

---

index.d.ts
test/types/types.test.ts

Fix for Missing Type issue: https://github.com/fastify/fastify-swagger/issues/626
_Now I'm worried I don't have a proper Certification of Origin_
Thanks for all the amazing work on Fastify!

Added missing SwaggerOptions.uiConfig.supportedSubmitMethods issue 626

---

lib/util/prepare-swagger-ui.js

The regex is used to evaluate and alter contents of `swagger-ui-dist`, that we have no control over.
They may decide to go all caps for some reason, so this provides a safeguard against that.

chore(prepare-swagger-ui): make regex case-insensitive

---

index.d.ts
test/types/types.test.ts

SwaggerUI has the ability to persist the authorization header into the local storage. Currently, our types don't support it.
This PR adds the property to `FastifySwaggerUiConfigOptions` type.
Reference: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

Add persistAuthorization swagger ui option

---

lib/mode/static.js
lib/spec/openapi/index.js
lib/spec/swagger/index.js
package.json
tap-snapshots/test/mode/static.js.test.cjs
test/hooks.js
test/route.js
test/spec/openapi/option.js
test/spec/openapi/route.js
test/spec/swagger/option.js
test/spec/swagger/route.js

https://github.com/fastify/fastify-swagger/pull/644#issuecomment-1202966258
I did not run any benchmarks. And it seems that the strings were using double quotes and Dates are outputted without quotes at all, which seems to be correct.

replace js-yaml with yaml

---

examples/collection-format.js

chore: replace use of deprecated variadic `listen()`

---

test/mode/static.js

`js-yaml` was replaced with `yaml` in https://github.com/fastify/fastify-swagger/pull/646.

test(mode/static): fix require

---

index.d.ts
test/types/swagger-ui-vendor-extensions.test.ts

Closes #654 
This PR adds the swagger ui vendor extensions x-tokenName.
There are two extensions. x-example and x-tokenName.
x-example does not need patching, because it is already covered by openapi-types. But I added typings tests to ensure, that they are possible. Didnt want that somebody comes tomorrow and says, they are missing... ;)
So this adds x-tokenName to the SecuritySchemas of OpenAPI v2 and v3.
ref: https://github.com/swagger-api/swagger-ui/pull/2587 (adding x-tokenName to OpenAPI2 in swagger-ui)
ref: https://github.com/swagger-api/swagger-js/pull/1489 (adding x-tokenName to OpenAPI3 in swagger-ui)
@fernandolguevara 

add swagger-ui vendor extensions, esp. x-tokenName

---

lib/util/common.js
test/spec/openapi/refs.js

Probably wont fix #634 and #633 because it just avoids the crashing of fastify-swagger. 
I think there is still some underlying issues on generating a proper output. But because we dont get a crash of fastify-swagger, people should report, if the generated schema is correct or not and fix it in a follow up issue/PR

avoid crashing of resolveLocalRef

---

README.md
lib/mode/dynamic.js
lib/mode/static.js
test/route.js

The purpose of this PR is to allow to define a specific log level in scenarios when we want to `silent` all logs of the swagger route.

feat: allow to define route log level

---

README.md

The proposal of this PR is update docs removing `logLevel` option because now silent log into swagger route is part of `fastify-swagger-ui`

docs: remove logLevel option

---

lib/spec/openapi/index.js
lib/spec/openapi/utils.js
test/spec/openapi/option.js

Hello everyone, in an attempt to fix issues #494 and #540 I integrated support for `server` relative and templated urls.
When `stripBasePath` was set to true then the server url was being parsed as is using `new URL(serverUrl)`. This inevitably resulted in an error when the server url was either relative (e.g. `/foo/bar`) or templated (e.g. `http://localhost:{port}/{basePath}`). 
The changes introduced by this PR solve the issue by first resolving the server url (by replacing templated variables with the corresponing values) and then by using it as is if relative or otherwise parsing it through `new URL(serverUrl)` in order to extract the pathname.
Fixes #494, Fixes #540

feat: add support for server relative and templated urls 

---

lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
package.json
test/spec/openapi/refs.js
test/spec/openapi/schema.js
test/spec/swagger/refs.js

Instead of just fixing the problem for `enum` (see #701), I assume we can pass everything from the JSON Schema into the OpenAPI parameter's spec.
See the last OpenAPI test for an, admittedly, contrived scenario, which may however show why it may be short-sighted to only render the `string` specific keywords (`pattern`, `format`, `minLength`, `maxLength`). [This test is only for demo purposes]
Whenever the type is not `string`, it may make sense to make to explicitly set the `style` property.
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameter-object
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#style-values
In the end, this is similar to …

fix: Pass JSON Schema keywords into OpenAPI Header Spec

---

README.md
lib/util/common.js
test/spec/swagger/schema.js

This PR partially reverts https://github.com/fastify/fastify-swagger/pull/649 due to some unintended breakage. I had a couple of applications whose tests failed badly due to the HEAD routes now included in the definitions. This PR hides by default but add an option to expose them, both at the plugin level or at the route level.
The plugin would rely anymore on the Fastify own settings.
Fixes #722 

Hide HEAD routes by default

---

index.d.ts
test/types/http2-types.test.ts
test/types/types.test.ts

I'll use CI to make sure `npm run test` and `npm run benchmark` are AOK. I can elaborate on *why* this change is necessary, but instead just look at the changes to the tests. BTW the example in the readme still works (once you change it by making `transformedSchema` be `...ts` then `const transformedSchema = ts as FastifySchema`).

Don't use JSONObject for `transform`.

---

README.md
index.d.ts
lib/spec/openapi/index.js
lib/spec/swagger/index.js
test/transform.js

Add `route`, `openapiObject`, and `swaggerObject` to the transform hook parameters.
Keeps `schema` and `url` as param to avoid breaking changes
```js
// openapi
await fastify.register(fastifySwagger, {
openapi: {},
transform: ({ schema, url, route, openapiObject }) => {
// do something with openapiObject
// do something with route e.g route.constraints.version
return {
schema: route.schema,
url: route.url
}
}
})
await fastify.register(fastifySwagger, {
swagger: {},
transform: ({ schema, url, route swaggerObject }) => {
// do something with swaggerObject
return { schema, url }
}
})
```
closes #737 access to version via `openapiObject.openapi` or `swaggerObject.swagger`
closes #732 access to route version via `route.constraints.version`
and the [Code of …

feat: add route, openapi and swagger objects to transform

---

README.md
index.d.ts
lib/spec/openapi/index.js
lib/spec/swagger/index.js
test/transform.js
test/types/types.test.ts

adds endpoint-specific transforms

---

lib/mode/static.js
lib/util/read-package-json.js
test/mode/static.js

See https://github.com/fastify/fastify-static/pull/407

perf: use `node:` prefix to bypass require.cache call for builtins

---

lib/util/add-hook.js
test/decorator.js

Fix race condition that have the spec cached if .swagger() is called before ready()

---

lib/spec/openapi/utils.js
lib/spec/swagger/utils.js
test/spec/openapi/schema.js
test/spec/swagger/schema.js

fix(openapi): support nullish consts

---

examples/options.js
lib/spec/openapi/utils.js
test/spec/openapi/option.js

Closes #728 
-  Since there is already an explanation of OpenApi options, I thought it unnecessary to add it to the README.

feat: support for webhooks option according to Open Api 3.1.0

---

README.md
lib/spec/openapi/index.js
lib/spec/openapi/utils.js
lib/spec/swagger/index.js
lib/spec/swagger/utils.js
lib/util/generate-params-schema.js
lib/util/match-params.js
test/spec/openapi/route.js
test/spec/openapi/schema.js
test/spec/swagger/route.js
test/spec/swagger/schema.js
test/util.js

Generate default param schema only if user doesn't specify a schema for param at all. If there is something, even with missing params, we should not modify it.
**Suggested solution**
- Check for params in the normalized url and for missing params in schema
- Generate a schema from the params found in the url
- Resolve params to the destination format using the previously generated schema
- Apply this behaviour to both specs
Closes https://github.com/fastify/fastify-swagger/issues/750

feat: generate path params definition when missing

---

lib/spec/openapi/utils.js
lib/util/generate-params-schema.js
lib/util/match-params.js

See https://github.com/fastify/fastify-autoload/pull/330

fix(lib): polynomial redos routes

---

lib/spec/openapi/utils.js
lib/util/resolve-local-ref.js
lib/util/resolve-swagger-function.js

See https://github.com/fastify/fastify-helmet/issues/236

refactor: replace `typeof` undefined check

---

lib/spec/openapi/utils.js
lib/spec/swagger/index.js
lib/spec/swagger/utils.js
test/spec/openapi/option.js
test/spec/swagger/option.js

Hello! I've started using this plugin and noticed some unexpected behavior while trying to use `openapi` config on `fastify.register`. I've tried to include `openapi.paths` config following your [options documentation](https://github.com/fastify/fastify-swagger#options) ([OpenAPI configuration](https://swagger.io/specification/#oasObject)) in order to include some additional paths to my Swagger object, but it had no effect. This PR fixes it.
Here's an example of what I'm trying to do with `openapi.paths`:
```js
await fastify.register(fastifySwagger, {
prefix: '/docs',
openapi: {
info: {
title: 'Fastify sample server',
description: 'Fastify sample api',
version: '0.1.0',
},
paths: {
'/status': {
get: {
description: 'Status route, so we can check if server is alive',
tags: [
'Status',
], …
```

fix: openapi/swagger options path

---

examples/options.js
lib/spec/openapi/utils.js
test/spec/openapi/route.js

Treat the `http` `bearer` auth security scheme the same as other security schemes by removing the `authorization` header.
Fixes #734

fix(openapi): hide auth header when set in securityScheme

---

lib/util/format-param-url.js
test/util.js

This plugin transforms the route "/example/*" into "/example/{wildcard}". Therefore, the schema for a route with a wildcard should be defined as follows:
```javascript
fastify.get(
"/example/*",
{
schema: {
params: {
wildcard: { type: "string" },
},
},
},
(request, reply) => {
const path = request.params["*"];
reply.send(path);
}
);
```
This pull request allows defining the schema for a route with a wildcard as expected:
```javascript
fastify.get(
"/example/*",
{
schema: {
params: {
"*": { type: "string" },
},
},
},
(request, reply) => {
const path = request.params["*"];
reply.send(path);
}
);
```
This resolves the issue discussed in [this GitHub issue](https://github.com/fastify/fastify-swagger/issues/773).
and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_C …

fix: * param renamed to wildcard

---

MIGRATION.md

See https://github.com/fastify/ajv-compiler/pull/115

docs(readme): replace `fastify.io` links with `fastify.dev`

---

lib/spec/openapi/utils.js
test/spec/openapi/refs.js

The `examples` keyword is never transformed to `example` for shared schemas (added via `fastify.addSchema` and referred with `$ref`).
This PR calls the appropriate function on preparation of these shared schemas.

Resolve examples for shared schemas
