fastify/fastify-swagger

index.js, test/swagger.js
Allow request headers to be declared in swagger
=> Include schema's request header configuration

README.md, example.js
The example on the README doesn't work, and does not match the one shown in `example.js`. This updates them to be the same.
/cc @delvedor
=> update README to match example

index.js
see: https://github.com/fastify/fastify-plugin/issues/17#issuecomment-355972265
=> Updates plugin-meta

dynamic.js, test/swagger.js
=> Allow 'security' on top scope

package.json
=> chore(package): update swagger-ui-dist to version 3.14.0

dynamic.js, test/swagger.js
I have added definitions support. All test passes. Plz add this.
=> Add definitions models support

README.md
=> Added reference to fastify-swaggergen to README.md

README.md, dynamic.js, test/swagger.js
=> Add missing tags and externalDocs top-level fields

tap-snapshots/test-static.js-TAP.test.js, test/route.js
Testing on windows is hard.
This looks ugly so feel free to close if you think it's unnecessary
=> Added platform specific slash

package.json, test/swagger.js
Greenkeeper failed to do this automatically due to various errors
=> Updated swagger-ui-dist and standard

tap-snapshots/test-static.js-TAP.test.js, test/route.js
Reverts fastify/fastify-swagger#105
cc @mcollina
=> Revert "Added platform specific slash"

index.d.ts, types.test.ts
=> Fix types for static mode (#139)

package.json
=> chore(package): update swagger-ui-dist to version 3.20.9

package.json
=> chore(package): update swagger-ui-dist to version 3.21.0

index.d.ts, types.test.ts
Allow using route schema swagger properties
=> feat(routeSchema types): Adds routeSchema types

http2-types.test.ts, index.d.ts, tsconfig.json
changed types to support http2
added a http2 types testfile
=> HTTP2 Support added

package.json
=> chore(package): update fs-extra to version 8.0.1

package.json
=> chore: update tap and greenkeepr ignore it

test/route.js
=> fix 404 check

package.json
This is an automatic PR created with massive-wax!
=> chore: greenkeeper ignore tap

index.d.ts, types.test.ts
=> Typescript: Support "RouteOptions.consumes" field

package.json
=> chore(package): update swagger-ui-dist to version 3.24.0

package.json
=> chore(package): update joi-to-json-schema to version 5.1.0

package.json
=> chore(package): update @types/node to version 12.11.7

README.md
=> Docs add an example swagger model definition to the options example

routes.js, test/route.js
Resolves https://github.com/fastify/fastify-swagger/issues/241 .
Looking forward to your feedback.
=> make redirects from the swagger root relative

dynamic.js, test/swagger.js
=> Include swagger extensions in final swagger documentation

examples/dynamic.js
Just add a code example from the readme to the file.
Ref #293 
=> added auth to example

README.md
Remove id and nullable options from `definitions.User` to avoid TS schema error.
=> Remove id and nullable options from definitions

README.md, index.d.ts, index.js, package.json, prepare-swagger-ui.js, test/integration.js, test/swagger.js
=> feat: :sparkles: add sha-256 hashes for csp

index.js, lib/dynamic.js, lib/openapi.js, lib/static.js, lib/swagger.js, package.json, tap-snapshots/test-static.js-TAP.test.js, test/openapi.js, test/route.js, test/static.js, test/swagger.js
=> updated js-yaml to v4

.github/workflows/ci.yml, README.md
Update example of helmet config as v5.2.0 of `fastify-helmet` adds support for CSP default directive exports
=> chore: documentation and ci updates

examples/options.js, lib/spec/openapi/utils.js, test/spec/openapi/option.js
=> fix: missing security field in openapi

README.md, package.json
Current description is misleading, as `fastify-swagger` is not just a specification generator.
=> docs(readme): Clarify purpose of the library

lib/util/common.js, test/util.js
=> fix #384 : underscore in parameters name

README.md
=> docs: update supported version

README.md
=> add missing comma

index.d.ts, test/types/types.test.ts
This should be really easy to review. 🙂
Refs: #406
=> fix: add hideUntagged to type definition

README.md
As highlighted by https://github.com/fastify/fastify-swagger/issues/397#issuecomment-816660852, the documentation for `fastify-swagger` is quite long (my scroll wheel gets a good workout going through it). This PR attempts to resolve this issue by removing or consolidating parts where possible, as well as improving the readability.
This PR changes the following:
- Removes excess example JavaScript and JSON objects used to convey functionality that a single sentence could
- Add `routePrefix` option to Register Options table (removing need for separate section)
- Removes "Security" section (The introducing sentence of the OpenAPI specification states it is purely for documentation, I do not think we need to repeat them)
- Rewrite of certain sentences and paragraphs to improve …
=> docs(readme): revamp documentation

index.d.ts, test/types/types.test.ts
I tried to use links properties in my routes definition and I realized that it doesn't have their type definition.
I'd like to contribute to this project and suggested this fix.
Please let me know if something is incorrect or incomplete. 
=> Add links property type to RouteShorthandOptions interface

index.d.ts, test/types/types.test.ts
=> add: uiHooks type definition #476

lib/spec/openapi/utils.js, lib/spec/swagger/utils.js, package.json, test/spec/openapi/schema.js, test/spec/swagger/schema.js
=> support fluent-json-schema for swagger and openapi

index.d.ts, test/types/types.test.ts
=> Add produces field to FastifySchema definition

README.md, lib/spec/openapi/utils.js, test/spec/openapi/schema.js
=> OpenAPI 3 Serialization options

lib/spec/openapi/utils.js, test/spec/openapi/schema.js
=> prevent mangling of object properties.

index.d.ts, test/types/types.test.ts
resolves https://github.com/fastify/fastify-swagger/issues/501
=> refResolver index.d.ts typescript typings

README.md, index.d.ts, lib/spec/openapi/index.js, lib/spec/swagger/index.js, test/spec/openapi/option.js, test/spec/swagger/option.js, test/transform.js, test/types/http2-types.test.ts, test/types/types.test.ts
resolves issue https://github.com/fastify/fastify-swagger/issues/555
combines the following PRs into one by enhancing the existing `transform` option:
https://github.com/fastify/fastify-swagger/pull/559
https://github.com/fastify/fastify-swagger/pull/560
=> feat(major): transform add url to option and document more possible use cases

lib/spec/openapi/utils.js, test/spec/openapi/schema.js
=> fix: respect patternProperties inner schema

README.md, lib/routes.js, package.json
=> fix: use new @fastify/static module to prevent deprecation warning

lib/spec/openapi/utils.js, lib/spec/swagger/utils.js, package.json, test/spec/openapi/schema.js, test/spec/swagger/schema.js
Wait until https://github.com/fastify/fastify/pull/3972 released in new version
Related #611 
=> Revert "fix tests (#610)"

lib/util/prepare-swagger-ui.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
Fixes #623 
=> Copy over index.css from swagger-ui

README.md, examples/collection-format.js
=> docs(readme): fix collectionFormat example (#636)

package.json
for reference [swagger-ui#8149](https://github.com/swagger-api/swagger-ui/pull/8149)
=> vendor(swagger-ui-dist): update dep version

.npmrc
=> disable package-lock.json generation

package.json
=> run lint on pre-commit

.taprc, package.json
Currently we are at 100% test coverage and we should enforce that
=> enforce test coverage check in .taprc

index.d.ts, test/types/types.test.ts
=> fix type definition for `fastify.swagger({ yaml: true })`

index.d.ts, index.js
=> make nodenext compatible

README.md, lib/spec/openapi/utils.js, test/spec/openapi/option.js
fix https://github.com/fastify/fastify-swagger/issues/625
=> fix `examples` in json schema

package.json
Similarly to [this PR](https://github.com/fastify/fastify-swagger-ui/pull/64) for `fastify-swagger-ui`, the goal of this PR is to update `yaml` to a [patched version](https://github.com/advisories/GHSA-f9xv-q969-pqx4)
=> fix(yaml): Update to patched version

lib/util/common.js, test/spec/swagger/schema.js
=> feat: support head routes

index.d.ts, test/types/types.test.ts
Details in issue.
Closes #729.
Might be a breaking change for some rare cases.
=> feat(ts): support readonly schema

README.md, index.d.ts, lib/mode/dynamic.js, lib/spec/openapi/index.js, lib/spec/openapi/utils.js, lib/spec/swagger/index.js, lib/spec/swagger/utils.js, test/transform.js
I've kept it similar to the `transform` hook to allow for additional parameters should we wish to add them in the future.
Resolves #736
=> feat: add transformObject hook

examples/options.js
=> chore(examples): add missing `use strict` directive

lib/util/resolve-local-ref.js
See https://github.com/fastify/fastify/pull/5057
=> perf(lib/util/resolve-local-ref): optimize split param

README.md
=> docs: fix wording

MIGRATION.md
=> docs(migration): fix broken link
